--------------------------------------------------------
--  File created - Wednesday-January-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "ASMADB"."CUSTOMER" 
   (	"CUSTOMER_ID" VARCHAR2(12 BYTE), 
	"CUSTOMER_NAME" VARCHAR2(20 BYTE), 
	"CUSTOMER_TYPE" VARCHAR2(10 BYTE), 
	"DISCOUNT" NUMBER(4,2), 
	"SKIN_TYPE" VARCHAR2(30 BYTE), 
	"HAIR_TYPE" VARCHAR2(30 BYTE), 
	"ALLERGY" VARCHAR2(15 BYTE), 
	"PHONE_NUMBER" VARCHAR2(18 BYTE), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"VISIT_COUNT" NUMBER, 
	"RATING" NUMBER(2,1), 
	"C_PASS" VARCHAR2(20 BYTE), 
	"LOGIN_STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUST_CUSID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASMADB"."CUST_CUSID_PK" ON "ASMADB"."CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CUST_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ASMADB"."CUST_ID" 
  BEFORE INSERT OR UPDATE ON customer
for each row
begin
    :new.customer_id := 'C-' || lpad(customer_id_seq.nextval,9,'0');
end;
/
ALTER TRIGGER "ASMADB"."CUST_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "ASMADB"."CUSTOMER" ADD CONSTRAINT "CUST_CUSID_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ASMADB"."CUSTOMER" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ASMADB"."CUSTOMER" MODIFY ("CUSTOMER_NAME" NOT NULL ENABLE);
  ALTER TABLE "ASMADB"."CUSTOMER" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
