--------------------------------------------------------
--  File created - Wednesday-January-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "ASMADB"."EMPLOYEE" 
   (	"E_ID" VARCHAR2(12 BYTE), 
	"E_NAME" VARCHAR2(20 BYTE), 
	"CONTACT_NUMBER" VARCHAR2(17 BYTE), 
	"HIREDATE" DATE, 
	"CURRENT_ADDRESS" VARCHAR2(60 BYTE), 
	"PERMANENT_ADDRESS" VARCHAR2(60 BYTE), 
	"SKILLS" VARCHAR2(200 BYTE), 
	"RATING" NUMBER(3,1), 
	"BONUS" NUMBER(10,2), 
	"SALARY" NUMBER(10,2), 
	"MANAGER_ID" VARCHAR2(12 BYTE), 
	"E_PASS" VARCHAR2(20 BYTE), 
	"LOGIN_STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index E_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASMADB"."E_ID_PK" ON "ASMADB"."EMPLOYEE" ("E_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger EMP_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ASMADB"."EMP_ID" 
 BEFORE  INSERT ON employee
for each row
begin
    :new.e_id:= 'Em-' || lpad(employee_id_seq.nextval,9,'0');
end;
/
ALTER TRIGGER "ASMADB"."EMP_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "ASMADB"."EMPLOYEE" ADD CONSTRAINT "E_ID_PK" PRIMARY KEY ("E_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ASMADB"."EMPLOYEE" MODIFY ("CURRENT_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "ASMADB"."EMPLOYEE" MODIFY ("CONTACT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ASMADB"."EMPLOYEE" MODIFY ("E_NAME" NOT NULL ENABLE);
